# Generated by Django 6.0.7 on 2026-07-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_auditlogentry_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
