# Generated by Django 4.2.7 on 2026-04-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_type', models.CharField(choices=[('url', 'URL'), ('text', 'Text'), ('contact', 'Contact / vCard'), ('wifi', 'WiFi'), ('sms', 'SMS'), ('email', 'Email'), ('phone', 'Phone'), ('location', 'Location')], max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('content', models.TextField()),
                ('qr_color', models.CharField(default='#000000', max_length=20)),
                ('bg_color', models.CharField(default='#ffffff', max_length=20)),
                ('qr_size', models.PositiveIntegerField(default=300)),
                ('qr_style', models.CharField(default='square', max_length=20)),
                ('image_b64', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
