# Generated by Django 4.2.7 on 2026-05-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='scan_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
