# Generated by Django 4.2.7 on 2026-07-01 01:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import qrapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0002_qrcode_scan_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(db_index=True, default=qrapp.models._gen_code, max_length=20, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('target_url', models.URLField(max_length=2000)),
                ('image_b64', models.TextField(blank=True, default='')),
                ('qr_color', models.CharField(default='#000000', max_length=20)),
                ('bg_color', models.CharField(default='#ffffff', max_length=20)),
                ('qr_style', models.CharField(default='square', max_length=20)),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dynamic Link',
                'verbose_name_plural': 'Dynamic Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('referer', models.URLField(blank=True, default='', max_length=500)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='qrapp.dynamiclink')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
