# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0005_alter_dynamiclink_user_alter_qrcode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
